name: Simple CI/CD Pipeline

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t lionelraseemela/nginx-react-hello:latest .

    - name: Push to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push lionelraseemela/nginx-react-hello:latest

    - name: Install OpenShift CLI
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        tar -xzf oc.tar.gz
        sudo mv oc /usr/local/bin/

    - name: Deploy to OpenShift
      run: |
        oc login ${{ secrets.OPENSHIFT_SERVER }} \
          --token=${{ secrets.OPENSHIFT_TOKEN }} \
          --insecure-skip-tls-verify=true
        oc project ${{ secrets.OPENSHIFT_PROJECT }}
        oc set image deployment/nginx-react-hello nginx=lionelraseemela/nginx-react-hello:latest --record
        oc rollout status deployment/nginx-react-hello

    - name: Get OpenShift route URL
      id: getroute
      run: |
        ROUTE=$(oc get route nginx-react-hello-route -o jsonpath='{.spec.host}')
        echo "route_url=https://$ROUTE" >> $GITHUB_OUTPUT


    - name: Verify deployment with Ansible
      run: |
        pip install ansible
        ansible-playbook ansible/verify-endpoint.yml \
          -e target_url=${{ steps.getroute.outputs.route_url }}

